### ISSUE TITLE
when 3 people are typing, the third person has no comma

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#12]
![image](https://user-images.githubusercontent.com/58587369/115917725-9c194300-a4b1-11eb-890d-b3b02eebf812.png)

**Comment by nkgardose** [comment]
Fixed this issue in this [commit](https://github.com/hc-institute-japan/Kizuna/commit/e224946385c12eea3e20511b6e9692e4f23c0b16)
