### ISSUE TITLE
Tutorial request: Show steps to compile kizuna from source code

### ISSUE THREAD

**Issue by var-che** [hc-institute-japan/Kizuna#133]
Hello.

I think that it would be useful to include in readme.md how to compile it from the source. 

Thanks.

**Comment by tatssato** [comment]
Hi there! thanks for this issue @var-che 

I'm really sorry that we don't have a friendly instruction in `readme.md`.
And thank you very much for raising this issue. 
We will work on this and will let you know once we have an instruction that you can read to compile kizuna and run it on your own device! 

Thank you!

**Comment by var-che** [comment]
Thank you so much. I really appreciate the effort you are putting into the project!

**Comment by tatssato** [comment]
Hello @var-che 

We have just added a simple README for now 😁
