### ISSUE TITLE
Only the latest message is getting read in Group Message

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#14]
1. Alice send 3 messages to the group
2. Bob opens the group chat
3. alice relaods her page
4. the latest message is the only message that is getting read

bug is that onSeen seems to only get triggered for the latest message.

**Comment by nkgardose** [comment]
Fixed this bug in this [commit](https://github.com/hc-institute-japan/Kizuna/commit/e6f1e46b9d20ee2b657537e625790509e90da928)
