### ISSUE TITLE
The VideoView component cannot be clicked in the GroupChatInfo Media page

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#16]
![image](https://user-images.githubusercontent.com/58587369/116381622-09c9c400-a850-11eb-9fe4-befc8045a52c.png)

**Comment by nkgardose** [comment]
Fixed this bug in this [commit](https://github.com/hc-institute-japan/Kizuna/commit/c4ea53d633255c76f66d460eddd028e7a78a14fd)
