### ISSUE TITLE
video preview thumbnail does not load

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#17]
1. Choose a video file in group chat
2. Thumbnail wont load

**Comment by tatssato** [comment]
choose a video and you will see that the thumbnail does not load up

**Comment by nkgardose** [comment]
Fixed this bug in this [commit](https://github.com/hc-institute-japan/Kizuna/commit/b06b234f5c68816537bef652c782a71c9a02058f)
