### ISSUE TITLE
multiple sending of files in p2p chat does not work properly

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#20]
1. charlie (localhost:8200) send 3 pictures to alice (localhost:8100)
2. alice receives 3 pictures
3. on Charlie's chat page, only 1 image is displayed.
4. Alice will have 3 images in the media tab, but charlie will only have 1 in the media tab of chat info.

![image](https://user-images.githubusercontent.com/58587369/116652303-e1f96e00-a9bf-11eb-9f64-67294084edef.png)

**Comment by mechanicko** [comment]
fixed
