### ISSUE TITLE
The emptyConversation page does not appear even if there is no conversation yet

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#24]
- This picture is the current page if there is no conversation which is a bug.

![image](https://user-images.githubusercontent.com/58587369/118248594-70511200-b4df-11eb-90e1-7c70f1ed8ad7.png)

- What we would really like to do is this

![image](https://user-images.githubusercontent.com/58587369/118248799-aee6cc80-b4df-11eb-9934-3815df7ca36c.png)

I think this is happening because of the code [here](https://github.com/hc-institute-japan/Kizuna/blob/a82094abe42c265a5a929e93469c9ed3ee9aae6c/ui/src/app/Conversations/index.tsx#L223)

When I removed the `p2pState !== undefined`, the emptyConversation appears again so I think this is something you can check @mechanicko

**Comment by mechanicko** [comment]
fixed in commit f511304f2bf75b52a2d54f5cc0980bb540db799b
