### ISSUE TITLE
The added contact does not get reflected in the list of contacts until the page is refreshed

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#25]
How to reproduce

1.  boot up 3 agents (alice and bob and charlie) with `npm run demo`
2. alice adds bob to her contact
3. the contact list page will not instantly reflect the added contact (unless the page itself is refreshed with `f5`)

The contact list page should update with the added contact right after the contact was added I think

**Comment by nkgardose** [comment]
Fixed with the following [changes](https://github.com/hc-institute-japan/Kizuna/commit/2b2e4a5ccfa6a8cf55559724d2d8530a3cd8b0fc)
