### ISSUE TITLE
The position of the menu in the Profile page is misplaced

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#26]
![image](https://user-images.githubusercontent.com/58587369/118654853-f349d380-b823-11eb-89d7-938b087fd004.png)

**Comment by nkgardose** [comment]
Fixed this bug in this [commit](https://github.com/hc-institute-japan/Kizuna/commit/3ffca15f23de10afa9d3dfac85db87c05d69b4dd)
