### ISSUE TITLE
The unread badge also appears on the sender's page in p2p Chat

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#28]
How to reproduce
1. boot up 2 agents
2. Alice adds Bob and vice versa
3. Alice sends a message to Bob
4. Alice goes back to the `home/messaging` (conversations list) page
5. On Alice's page, un-read badge also appears (This is a bug since Alice should not have the unread badge for messages she sent)
6. If bob reads the message, the unread badge on Alice's page disappears as well.

**Comment by mechanicko** [comment]
fixed in 72b967d7adc7692c3b92aab508d15806ddfca5ad
