### ISSUE TITLE
remove self from the search of username

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#29]
How to reproduce
1. boot up an agent (alice)
2.  alice opens the add contact modal
3. when alice searches for her own username, it appears
4. alice can add her self (which result into other quirky bugs in typing signals and etc)

I think for the sake of prototype, we should remove one's own username from the add contact modal.
This should be an easy filter that can be done in the ui.

**Comment by nkgardose** [comment]
Implemented this enhancement feature in this [commit](https://github.com/hc-institute-japan/Kizuna/commit/52833cd9381776d50bebe935b101a48c2e228ca6)
