### ISSUE TITLE
Only fetch the file bytes for video when the play button is pressed

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#30]
Right now, video file bytes are getting fetched right away in the chatbox. This may result in a significant performance slow down when multiple video files are sent in succession. 

As per @nkgardose's suggestion, we should probably just fetch the file bytes once the play button has been pressed in the chatbox.

**Comment by nkgardose** [comment]
Implemented this feature in this [commit](https://github.com/hc-institute-japan/Kizuna/commit/b06b234f5c68816537bef652c782a71c9a02058f)
