### ISSUE TITLE
The AddGroupMemberModal turns into white after a member is added

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#35]
![image](https://user-images.githubusercontent.com/58587369/119298854-ccaef100-bc98-11eb-9c9c-bec6c3a9ea00.png)

**Comment by tatssato** [comment]
How to replicate 
1. `npm run demo-5`
2. alice adds bob/charlie/david/eve in her contacts 
3. alice creates a group chat only with bob and charlie
4. alice goes to the groupChatInfo page and opens the AddMemberModal by pressing the "Add Members" button
5. alice select david and eve (or can just be david or ever) in the modal
6. alice presses "Add"
7. The modal will turn white

I think I was trying to close the modal when "Add" button was pressed.
HOWEVER, I think it can just behave as how the AddContactModal behaves when a member was added. 
Which basically does not close the modal at all even a contact was added; so if we can have this modal not close and simply have a toast that says "david" or "eve" was added then that should be enough to close this issue.

P.S. I think I could have used more reusable components instead of making my own so apology in advance if your eyes hurt.
P.P.S. It would be nice if the code could be turned much cleaner and simpler (but this could just be an enhancement later on if we need to kick it down the road)

**Comment by nkgardose** [comment]
Fixed this bug in this [commit](https://github.com/hc-institute-japan/Kizuna/issues/35)
