### ISSUE TITLE
The video bytes is not being fetched when the P2P ChatDetails page (Filebox for Media page) is being refreshed

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#37]
1. `npm run demo`
2.  Alice adds Bob
3.  Bob adds Alice
4. Alice sends a video
5. Bob goes to ChatDetail/MEDIA tab
6. Bob sees the video sent
7. Bob refreshes the ChatDetail page
8. The video thumbnail is gone (Bug)
9. The video cant also be played (Bug)

**Comment by tatssato** [comment]
This bug is almost fixed, it's just the black thumbnail thing that is happening in chrome that is remainig as a bug

**Comment by mechanicko** [comment]
Instead of fetching the file bytes to display the video in the MediaBox, use thumbnail (included in the message structure) instead. Only fetch file bytes when the video is played. Both implementations have been done by @nkgardose.

**Comment by mechanicko** [comment]
In MediaBox, use VideoPlayer component instead of VideoView.

**Comment by tatssato** [comment]
This has been worked on with a25138682af5aa7517839bdac797fdea60058176 so I will close this issue now :D
