### ISSUE TITLE
P2P chat box is not at the bottom when the page is refreshed

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#38]
Try to send a lot of message in p2p chat then hit refresh in browser.
The chat box should scroll to bottom or be at the bottom but right now, when it is refreshed, the scroll is on top

**Comment by mechanicko** [comment]
attempt fix in d123d3dcc7ad6de5ca07040b28661df91d47ff77

**Comment by tatssato** [comment]
I confirmed that this is working already with 084ed95543e47a9d1eac122aeb124b4f7505f78f
