### ISSUE TITLE
The AddContact modal does not open again after the first try when the modal was closed by clicking the page behind it

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#40]
1. `npm run demo`
2.  alice opens the add contact modal
3.  alice closes the modal by clicking the page behind the modal
4.  Even if alice presses the add contact modal button, the modal does not open

**NOTE: This does not happen if the arrow back button is pressed to go back to the previous page. Therefore, this behaviour does not happen in a mobile setting because the modal is in a full screen. This only happens in a browser setting when alice can press the page behind the modal so this may actually not be a bug?**

**Comment by nkgardose** [comment]
Fixed this bug in this [commit](https://github.com/hc-institute-japan/Kizuna/commit/bc851d32b67e876ba0891fc96bf937785a260ec2)
