### ISSUE TITLE
Allow sending of files by pressing enter key as well

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#44]
Right now, files can only be sent by pressing the sent button. It will be nice also for files to be sent with enter key just like how we are sending texts with enter key aotm.

**Comment by nkgardose** [comment]
Fixed this issue in this [commit](https://github.com/hc-institute-japan/Kizuna/commit/45690e537fb148b9232c5abc4f396fc15f97aaf6)
