### ISSUE TITLE
The typing indicator is blinking when an agent types on and off for a while

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#45]
This happens both for group chat and p2p chat (as the implementation of debouncing and calling of typing indicator function is similar)
how to reproduce in group chat
1. `npm run demo`
2. `alice` adds `bob` and `charlie
3. alice creates a group chat with bob and charlie
4.  `alice` keeps typing on and off (see video attached)
5. the typing indicator on bob's screen will start to blink
how to reproduce in p2p chat
1. `npm run demo`
2. `alice` adds `bob` 
3. `bob` adds `alice`
3.  alice creates a chat with bob
4. alice` keeps typing on and off (similar to how it is in group)
5. the typing indicator on bob's screen will start to blink

https://user-images.githubusercontent.com/58587369/120577879-dd612300-c45f-11eb-8606-1634adff4adf.mov

**Comment by nkgardose** [comment]
Fixed this bug in this [commit](https://github.com/hc-institute-japan/Kizuna/commit/32c06055f2caed142a5856b3870b87b12ac4d20a)
