### ISSUE TITLE
Change breaking of line to Shift + Enter instead of Enter

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#46]
Right now, breaking of line and sending of message is the same key (Enter key) so when we send a message the line breaks as well. 

Let's change it to
Sending of message - Keep it as Enter key
Breaking of line - Change to _Shift + Enter_

**Comment by nkgardose** [comment]
Implemented this feature in this [commit](https://github.com/hc-institute-japan/Kizuna/commit/45690e537fb148b9232c5abc4f396fc15f97aaf6)
