### ISSUE TITLE
[p2p] Sending a file and a text message at the same time fails for p2p [Attempted to commit a bundle to the source chain, but the source chain head has moved]

### ISSUE THREAD

**Issue by mechanicko** [hc-institute-japan/Kizuna#52]
Error type: internal_error - source chain error
Error message: Workspace error: Attempted to commit a bundle to the source chain, but the source chain head has moved since the bundle began. Bundle head: Some(HeaderHash(uhCkkbmO2OwXuEbJEYkq5kaWRKaTvwKcpYbKRBKNU7uyCaJnQOQ9Q)), Current head: Some(HeaderHash(uhCkk69hzfNldF6zKs6cnWofUgZl6eH7mYS1S4xdUepThCg0AMPXe))

How to replicate:
Method 1
1. Setup two agents
2. Send a file/image/video together with a text message from Agent A to Agent B
3. This will cause an error in Agent A's side. Either the message or the file will not be sent.

Method 2
1. Setup two agents.
2. Send text messages in quick succession from Agent A to Agent B.
3. This will cause an error in Agent A's side. One (or more) of the text messages will fail to send.

**Comment by tatssato** [comment]
As a workaround to this, I believe we should have a function in p2p zome that _solely recommit the uncommitted entry_. (something with a name like `retry_commit`) This function can either be called from the ui when the sender's or receiver's conductor fails to commit the message entry to the source chain. Further discussion is needed on whether we will implement this in the frontned or holochain layer (if that is even possible)

**Comment by mechanicko** [comment]
Moved the call to commit the text message ahead of the file message and implemented a timeout between the two calls.
