### ISSUE TITLE
Type-ahead handle search is case-sensitive

### ISSUE THREAD

**Issue by pdaoust** [hc-institute-japan/Kizuna#92]
Expected behaviour: I type in 'hol' and I should find the username of my acquaintance 'Holoptik'.

Observed behaviour: I have to type in 'Hol' to find 'Holoptik'.

**Comment by tatssato** [comment]
Thanks for trying kizuna prototype out @pdaoust!
Hmm, this is interesting, we are constructing a path out of the input of the user so 'hol' and 'Hol' would result in different `Path` hash. We could automatically get both 'hol' and 'Hol' when a user searches but then we won't be able to get the results when nickname such as 'hOl' or 'HOL' exist as path in profile modules [instantiates](https://github.com/holochain-open-dev/profiles/blob/main/zome/src/profile.rs#L111) with the first 3 characters of the nickname. 

I will discuss this with guillem and see what we can do. 
we could permute all sequence of upper and lowercase character of the search input and call `get_links` in parallel but that can get quite expensive quite easily...
But for now, we will have `hol` search for `Hol` and `hol` as well :D

**Comment by tatssato** [comment]
This has been fixed with [this](https://github.com/holochain-open-dev/profiles/pull/6) PR in profiles-module 😁
